[package]
name = "ggez-goodies"
description = "Various small useful add-ons for the ggez game framework"
version = "0.1.0"
repository = "https://github.com/icefoxen/ggez-goodies"
documentation = "https://docs.rs/ggez-goodies"
authors = ["Simon Heath <icefoxen@gmail.com>"]
license = "MIT"
readme = "README.md"


[dependencies]
#ggez = { path = "/home/icefox/src/ggez" }
ggez = { git = "https://github.com/ggez/ggez", branch = "master" }
rand = "0.3"
nalgebra = "0.10"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
serde-xml-rs = "0.1"

