[package]
name = "ggez-goodies"
description = "Various small useful add-ons for the ggez game framework"
version = "0.1.0"
repository = "https://github.com/icefoxen/ggez-goodies"
documentation = "https://docs.rs/ggez-goodies"
authors = ["Simon Heath <icefoxen@gmail.com>"]
license = "MIT"
readme = "README.md"


[dependencies]
ggez = "0.4.0"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
any-cache = "0.2"
notify = "4.0"
